addons:
  apt:
    packages: # needed for windres et.al. in launch4j
    - lib32z1
    - lib32ncurses5
notification:
  email:
    on_success: never
    on_failure: always
language: clojure
lein: lein
before_install:
- rvm install 2.4.1
- gem install travis-custom-deploy
before_script:
- sh -e /etc/init.d/xvfb start
# install launch4j
- bin/install_launch4j.sh

script:
  - lein deps
  - lein test
  - lein uberjar
  - lein launch4j

after_success:
- travis-custom-deploy sftp target/mincer-3.2.1-standalone.jar target/mincer-3.2.1.exe
env:
  global:
  - DISPLAY=:99.0
  - EXT_DIR="${TRAVIS_BUILD_DIR}/ext"
  - LAUNCH4J_INSTALL_DIR="${EXT_DIR}/launch4j"
  - secure: Io8YMQTY/kP08xvp37ZTPY4zoHp2zSxIqw8VMcyQBBQddLuw7D4EO6OLm/H+1V+TBfwscP1jLJwh5/D9fTTHvctNBiukWifJ8DLW2J74H++bm3ZeFfIYWe1CtflvkdVUUAnpGQPAoco+yrTC+rC+ZOASJNj38dMlIiM7HpgXTdfUNKiMnkF26qISUq9gOI6Zv0VMfF1LXPA+cBirPyxlwotpahJNqo1F69MT5shdTWktMmzAgLKHgHXdgYI9JU+yVmJ2YhIeT54jiSitORWE+F1CCKXiPwfBBEgd/a+813t3qzMDRbIaEkDH4EAqMogo7I2mJJspdabI3WjNKhIrFZMyphx+O5PMAw+HZSb2gIkGHguNispfVvsiLlJIdnywAOugtwEHlUHqvUNnBN8hsYuS976cCCpFDxFqLXoHUNmH8N6HkOq9qqeVMZ8n1pE75b9ShcJg06efcxiKvTwplP4qOOVr8SIZvvb4xVDjSCDcgppAEy5C4ccg7qgfVlWuKVJq7p9sOr2rvfuHUSkVrj3FaYAtk71Pp/dq2U/9Qf3EdNCYuMRqE1dEeo86+Rr+NxwTLkBFUra30xfh7Ii/XKd1TBcApdIx1IQRVGdMt7Mf27+0sNC2Hpa+RH2RpZQ/49014BeWCKbpDw7k/La5cW7e9ypDez89mdHkS5hzHSw=
  - secure: o17LJrUYPKoOs759cUmCHT4YlzQwqoGIhw6zLHbo4u8WSdmrepVnGKI9A0OgIlZvwVBs0Fnbvn5cGKiVGHZ3nqoPK8J5CypxC+pB/s/KsVAg+KlYNYN8xQssSIos/ewvfFlWJ76UoxB87G6XGaXYTefiEGmlTR0ArOTbQfleXQpf6yyjsW528B9DIZ6qBAfNu3ukiD8TPmt00RgAPIFKD50Ftph+zQXP/VVDZ1V2WP/NXO22R9nnTIEY4PQ6JAUDFjwHO7O+e+40DpxSd9QBDfgmHUHgjQouZyhirmpLDeUa2anyfCu9uGiGfnP5XQq6bKhHhrBh++/8VaYlg4PoML/Mzwjv5fbOSUBIClVkhcqArEg2DgP/dGXIRH/QSwMzBxfeJVo2u5CdfIHNbXSLmBHlEUclbrBmvnE7ZW3ZfNc2Edj25ws48OAZFOKoeqwr06h4KL6zVweyWHuSKFdagvCdu5jWMCkXsX0L6zMvFV6nJNQDsVFzcRSIPaD68OM5lc6jLGi/BNBiwIZIjTP1WnC9MGdYb/YgjjUx6rVfDJV6wLPbeSQNYmsD26oTZL5Iy5I2yw7ev55jL2+phbyZcyD3zJFbItKnzUOo3kULjzXImgWX9ur/qtclKKOAEnGAqKoWyWlNv/HcttTodBUxvK2NL64HVDldATp1rAVuOlE=
  - secure: vm2KrTpgmAnava+NSHTjy1/yu4FFmszvoPXNW1+SIW5hcN3KrcpOLdIBMY5/SdzqF6yr26OgG7+UljLFu0FjKdVe7Dfj4Lvwe2u6x+R37G4vxF2b+wyJYOa7xRNzS7yKdAoWDzn0KbaUYvJ/JiHVnJNffWVQy5Ix52QbSv+QIIVCklpIbNUB3rqhdx4lkOJTqvaqSnBhz/MF6NI9pUwmZt+WDdu02BOKpSdVAUn0ZjeaZNMJ45bf1aTZyRlWOFMKFRG91mfhJ1BhWHwC1huOplKaun7uZrLckel71Bu44tGHKuzKl1WzsnoyXh+Hl3tefGX5aUkm3oLfrd3oLUvSczGiG5bFqp0vG2IcYGiPAGEs4JiAKlqd0llrp8qc8pKHR1+5nf63PBfA+gu13EOHgI+dPohBHZRsDmxImvAaypl6CE5Q+/eeJ563aAgQblv2DWAkarSCquzH6tnP1FX1iIe9FVFjh6aDI/sSU9Er8lTbhIV1PnU32rKvp/nUOo/bVCzHKIRd/RgNTJbEynFLF0xFTPAuEFPaVuif5NJoUbrXz3NX4OHt+b8FONqBxDukQeOJwmoTRPDm4wRHs/EmNa8HViBb7ls3tTc54IIGt62T1le7lD+3JJqYSTgFwICRIZgX19vy9Rjnin3Xi10otyKPhZuP1iotvUq2DF+DrSw=
  - secure: jbaeDzkIt4XDUAncus3fzCAPOMagYW/EOIeuRPvkej7/h5TxgvHOSXhk2wmfLW1g3Hu9tqP0/Q2Yiu/fJpB56Hr5lhjz+45Rsa9G68sewbsprPF+rEMjf9M4A5wQ3GchZ+nKhwDcUu9dw8M1VfhKqDtl8l1q/zEJxpHXW78ThO3gxLYJQQCBGJcIY9S83ei5FFQPlmt369lk+jSL5Js/4NI9IyoSTgILRI9aceLgod6ifGb9p8qtZyjUyyqWdHnIBNxXpdjOXj//GmcBx4ZN7FteBBuq0Oeaj7FZGV8H+VspSHLf0515oe9j9sFf/foUvMEoRERxVivQG94otTQtm7owPNraXu2ZOiNja/endoHg3cgkmnK4ZwKp7pOGPSL5CCgp6URyAT3rnWcrfQr4VCOKZTf+EwPvtVEUgUkk6MXbpQRg2aFqtq4L6St6yqsvFjm9E6X5eTaioMCNcmmSxm/VmJRxYaw9oYnHs696KGCxm7SySQESWAzUL2lR79XoVJxRUAoeDPmtLIcDvYeU+dNL6w9tkPp11bRKftP5MF9UTUBPA+znsv1jSlFDwpBtIc9yjpOHNbsoozIzsp78A+tydgcMcQ/gQLb9wNvk/LUlZUoXCHJpgYfV6K+CD0p8WqebhgI34qfGf98iLzk529e9+RtfPQPuqH4q2rer0bw=
notifications:
  slack:
    secure: jZgNPYs1JdikjAlb8XMregqIU75NJXWi4iZmzATYG5yKvlx7lK5dEYkE1Y2DIImeaS9v93/j6jvX2iw/GL+C2hDjQ7QO1lvsoOAewe2lLqvpvPXfrTK0vW2zyONCBXnK3k0OBd1cRM8oEAt4qv3ckwFaSiHiCsA69qW+n8kmJuQsCHFGtlH8hLUTW6AzWX1Vy1y1GMxzgFFRnrY8v1sT+54576w/9j6FQGrNhY3LPu59iPxDiHbx8zUToOwZSW76CwIx6qQGZjDr/1ZvbNsBCMkR2Oh/Ya55Z0vRbi5yk/1AgPCr42WvSaNq0wDrVZdLSpC9LbSR8eo4P7ilVvYTYemQQ4dalX2foJwme3hiSuQEgG51pBxYQiU5JWnuEWGKJh2e6zHYHaGCAVOrbyFFv178Wb48LotABRThUoCclRgXE0pTkHSlrFGYF0cAoqRsAX8ZTupI28bnHJnMX9d2zdotTwi90wqiQb3xlAkiAvTBSWxGgkt1KlG04Xv2xyWD8HKVHuo9LnPvHailnnOKJCo+sXd+MjHiLiyZOFjgXH73XI2RkWg627P5WosclfShQEmLNCV8OTyQFfqrBBhXAhRsw8JeKIu3W46YlD9EHM2kV0Zxi4HTLRyMQV5kf1t6C4v4qcr4W+KVETyx1K/50xBWi4WqoKgMLpfXBK+mXqY=
